package mmanm;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.spec.AlgorithmParameterSpec;
import java.security.spec.KeySpec;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.CipherOutputStream;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import javax.crypto.spec.DESedeKeySpec;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.apache.commons.io.FilenameUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class mm extends javax.swing.JFrame {

    /**
     * Creates new form mm
     */
    public mm() {
        initComponents();
        setResizable(false);
        //pack();
        //setLocationRelativeTo(null);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_RSA_btn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_AES_btn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_DES_btn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_MD5_btn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel_Working_Space = new javax.swing.JPanel();
        jPanel_Mainpage = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel_AES = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_input_AES = new javax.swing.JTextField();
        jButton_input_AES_btn = new javax.swing.JButton();
        jPanel_RSA = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_input_RSA = new javax.swing.JTextField();
        jButton_input_RSA_btn = new javax.swing.JButton();
        jPanel_DES = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_input_DES = new javax.swing.JTextField();
        jButton_input_DES_btn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_input_DES_key = new javax.swing.JTextField();
        jButton_input_DES_key_btn = new javax.swing.JButton();
        jButton_decrypt_DES_btn = new javax.swing.JButton();
        jButton_encrypt_DES_btn = new javax.swing.JButton();
        jPanel_MD5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_input_hash_1 = new javax.swing.JTextField();
        jTextField_output_hash = new javax.swing.JTextField();
        jButton_input_hash_btn_1 = new javax.swing.JButton();
        jButton_Hash_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField_input_hash_2 = new javax.swing.JTextField();
        jButton_input_hash_btn_2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField_output_hash_1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(24, 24, 24));

        jPanel1.setBackground(new java.awt.Color(44, 79, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(34, 64, 105));

        jPanel_RSA_btn.setBackground(new java.awt.Color(34, 64, 105));
        jPanel_RSA_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 79, 128)));
        jPanel_RSA_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel_RSA_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_RSA_btnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RSA");
        jPanel_RSA_btn.add(jLabel4);

        jPanel_AES_btn.setBackground(new java.awt.Color(34, 64, 105));
        jPanel_AES_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 79, 128)));
        jPanel_AES_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_AES_btnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AES");
        jPanel_AES_btn.add(jLabel1);

        jPanel_DES_btn.setBackground(new java.awt.Color(34, 64, 105));
        jPanel_DES_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 79, 128)));
        jPanel_DES_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_DES_btnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DES");
        jPanel_DES_btn.add(jLabel3);

        jPanel_MD5_btn.setBackground(new java.awt.Color(34, 64, 105));
        jPanel_MD5_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 79, 128)));
        jPanel_MD5_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_MD5_btnMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MD5");
        jPanel_MD5_btn.add(jLabel9);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mmanm/icon1.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AES_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_RSA_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_DES_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_MD5_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addGap(57, 57, 57)
                .addComponent(jPanel_AES_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_RSA_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_DES_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_MD5_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 480));

        jPanel_Working_Space.setBackground(new java.awt.Color(30, 144, 255));
        jPanel_Working_Space.setLayout(new java.awt.CardLayout());

        jPanel_Mainpage.setBackground(new java.awt.Color(44, 79, 128));
        jPanel_Mainpage.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel_MainpageAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(44, 79, 128));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(44, 79, 128));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Mật mã và an ninh mạng");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel19.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mmanm/icon2.png"))); // NOI18N
        jLabel19.setText("Lâm Võ Quang Trường");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mmanm/icon2.png"))); // NOI18N
        jLabel20.setText("Vũ Ngọc Thiên Long");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mmanm/icon2.png"))); // NOI18N
        jLabel21.setText("Nguyễn Văn Hiển");

        javax.swing.GroupLayout jPanel_MainpageLayout = new javax.swing.GroupLayout(jPanel_Mainpage);
        jPanel_Mainpage.setLayout(jPanel_MainpageLayout);
        jPanel_MainpageLayout.setHorizontalGroup(
            jPanel_MainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_MainpageLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(jPanel_MainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_MainpageLayout.setVerticalGroup(
            jPanel_MainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainpageLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel_Working_Space.add(jPanel_Mainpage, "card2");

        jPanel_AES.setBackground(new java.awt.Color(44, 79, 128));
        jPanel_AES.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel_AESAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(44, 79, 128));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 79, 128));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Advanced Encryption Standard");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Input:");

        jTextField_input_AES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_input_AESMouseClicked(evt);
            }
        });
        jTextField_input_AES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input_AESActionPerformed(evt);
            }
        });

        jButton_input_AES_btn.setBackground(new java.awt.Color(34, 64, 105));
        jButton_input_AES_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_input_AES_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_input_AES_btn.setText("Select File");
        jButton_input_AES_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_input_AES_btnMouseClicked(evt);
            }
        });
        jButton_input_AES_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_input_AES_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_AESLayout = new javax.swing.GroupLayout(jPanel_AES);
        jPanel_AES.setLayout(jPanel_AESLayout);
        jPanel_AESLayout.setHorizontalGroup(
            jPanel_AESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AESLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextField_input_AES, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_input_AES_btn)
                .addGap(25, 25, 25))
        );
        jPanel_AESLayout.setVerticalGroup(
            jPanel_AESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AESLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_AESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_input_AES, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_input_AES_btn)
                    .addComponent(jLabel14))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jPanel_Working_Space.add(jPanel_AES, "card2");

        jPanel_RSA.setBackground(new java.awt.Color(44, 79, 128));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(44, 79, 128));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 79, 128));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("RSA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Input:");

        jTextField_input_RSA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_input_RSAMouseClicked(evt);
            }
        });
        jTextField_input_RSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input_RSAActionPerformed(evt);
            }
        });

        jButton_input_RSA_btn.setBackground(new java.awt.Color(34, 64, 105));
        jButton_input_RSA_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_input_RSA_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_input_RSA_btn.setText("Select File");
        jButton_input_RSA_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_input_RSA_btnMouseClicked(evt);
            }
        });
        jButton_input_RSA_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_input_RSA_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_RSALayout = new javax.swing.GroupLayout(jPanel_RSA);
        jPanel_RSA.setLayout(jPanel_RSALayout);
        jPanel_RSALayout.setHorizontalGroup(
            jPanel_RSALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_RSALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jTextField_input_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_input_RSA_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_RSALayout.setVerticalGroup(
            jPanel_RSALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RSALayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_RSALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_input_RSA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_input_RSA_btn)
                    .addComponent(jLabel15))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jPanel_Working_Space.add(jPanel_RSA, "card2");

        jPanel_DES.setBackground(new java.awt.Color(44, 79, 128));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(44, 79, 128));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 79, 128));
        jLabel5.setText("Data Encryption Standard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(210, 210, 210))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField_input_DES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_input_DESMouseClicked(evt);
            }
        });
        jTextField_input_DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input_DESActionPerformed(evt);
            }
        });

        jButton_input_DES_btn.setBackground(new java.awt.Color(34, 64, 105));
        jButton_input_DES_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_input_DES_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_input_DES_btn.setText("Select File");
        jButton_input_DES_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_input_DES_btnMouseClicked(evt);
            }
        });
        jButton_input_DES_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_input_DES_btnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Input:");

        jLabel18.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Key:");

        jTextField_input_DES_key.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_input_DES_keyMouseClicked(evt);
            }
        });
        jTextField_input_DES_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input_DES_keyActionPerformed(evt);
            }
        });

        jButton_input_DES_key_btn.setBackground(new java.awt.Color(34, 64, 105));
        jButton_input_DES_key_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_input_DES_key_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_input_DES_key_btn.setText("Select File");
        jButton_input_DES_key_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_input_DES_key_btnMouseClicked(evt);
            }
        });
        jButton_input_DES_key_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_input_DES_key_btnActionPerformed(evt);
            }
        });

        jButton_decrypt_DES_btn.setBackground(new java.awt.Color(34, 64, 105));
        jButton_decrypt_DES_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_decrypt_DES_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_decrypt_DES_btn.setText("Decrypt");
        jButton_decrypt_DES_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_decrypt_DES_btnMouseClicked(evt);
            }
        });
        jButton_decrypt_DES_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_decrypt_DES_btnActionPerformed(evt);
            }
        });

        jButton_encrypt_DES_btn.setBackground(new java.awt.Color(34, 64, 105));
        jButton_encrypt_DES_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_encrypt_DES_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_encrypt_DES_btn.setText("Encrypt");
        jButton_encrypt_DES_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_encrypt_DES_btnMouseClicked(evt);
            }
        });
        jButton_encrypt_DES_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_encrypt_DES_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DESLayout = new javax.swing.GroupLayout(jPanel_DES);
        jPanel_DES.setLayout(jPanel_DESLayout);
        jPanel_DESLayout.setHorizontalGroup(
            jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_DESLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DESLayout.createSequentialGroup()
                        .addComponent(jTextField_input_DES, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_input_DES_btn))
                    .addGroup(jPanel_DESLayout.createSequentialGroup()
                        .addGroup(jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_input_DES_key, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DESLayout.createSequentialGroup()
                                .addComponent(jButton_encrypt_DES_btn)
                                .addGap(99, 99, 99)
                                .addComponent(jButton_decrypt_DES_btn)
                                .addGap(100, 100, 100)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_input_DES_key_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_DESLayout.setVerticalGroup(
            jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DESLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_input_DES, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_input_DES_btn)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_input_DES_key, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_input_DES_key_btn)
                    .addComponent(jLabel18))
                .addGap(92, 92, 92)
                .addGroup(jPanel_DESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_decrypt_DES_btn)
                    .addComponent(jButton_encrypt_DES_btn))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel_Working_Space.add(jPanel_DES, "card2");

        jPanel_MD5.setBackground(new java.awt.Color(44, 79, 128));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(44, 79, 128));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 79, 128));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MD5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input 1:");

        jLabel10.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Output 2:");

        jTextField_input_hash_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_input_hash_1MouseClicked(evt);
            }
        });
        jTextField_input_hash_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input_hash_1ActionPerformed(evt);
            }
        });

        jTextField_output_hash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_output_hashActionPerformed(evt);
            }
        });

        jButton_input_hash_btn_1.setBackground(new java.awt.Color(34, 64, 105));
        jButton_input_hash_btn_1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_input_hash_btn_1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_input_hash_btn_1.setText("Select File");
        jButton_input_hash_btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_input_hash_btn_1MouseClicked(evt);
            }
        });
        jButton_input_hash_btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_input_hash_btn_1ActionPerformed(evt);
            }
        });

        jButton_Hash_btn.setBackground(new java.awt.Color(34, 64, 105));
        jButton_Hash_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Hash_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Hash_btn.setText("Hash");
        jButton_Hash_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Hash_btnMouseClicked(evt);
            }
        });
        jButton_Hash_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Hash_btnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Input 2:");

        jTextField_input_hash_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input_hash_2ActionPerformed(evt);
            }
        });

        jButton_input_hash_btn_2.setBackground(new java.awt.Color(34, 64, 105));
        jButton_input_hash_btn_2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_input_hash_btn_2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_input_hash_btn_2.setText("Select File");
        jButton_input_hash_btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_input_hash_btn_2MouseClicked(evt);
            }
        });
        jButton_input_hash_btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_input_hash_btn_2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Output 1:");

        jTextField_output_hash_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_output_hash_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MD5Layout = new javax.swing.GroupLayout(jPanel_MD5);
        jPanel_MD5.setLayout(jPanel_MD5Layout);
        jPanel_MD5Layout.setHorizontalGroup(
            jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_MD5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25)
                .addGroup(jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_input_hash_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(jTextField_input_hash_1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_output_hash)
                    .addComponent(jTextField_output_hash_1))
                .addGap(18, 18, 18)
                .addGroup(jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_input_hash_btn_1)
                    .addComponent(jButton_input_hash_btn_2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MD5Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jButton_Hash_btn)
                .addGap(378, 378, 378))
        );
        jPanel_MD5Layout.setVerticalGroup(
            jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MD5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_input_hash_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_input_hash_btn_1))
                .addGap(4, 4, 4)
                .addGroup(jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_input_hash_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_input_hash_btn_2))
                .addGap(32, 32, 32)
                .addGroup(jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_output_hash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_MD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_output_hash_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton_Hash_btn)
                .addGap(44, 44, 44))
        );

        jPanel_Working_Space.add(jPanel_MD5, "card2");

        jPanel1.add(jPanel_Working_Space, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 780, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_DES_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_DES_btnMouseClicked
        // TODO add your handling code here:
        jPanel_DES_btn.setBackground(Color.decode("#2C4F80"));
        jPanel_AES_btn.setBackground(Color.decode("#22416B"));
        jPanel_RSA_btn.setBackground(Color.decode("#22416B"));
        jPanel_MD5_btn.setBackground(Color.decode("#22416B"));
        jPanel_Working_Space.removeAll();
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();

        jPanel_Working_Space.add(jPanel_DES);
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();
    }//GEN-LAST:event_jPanel_DES_btnMouseClicked

    private void jPanel_AES_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AES_btnMouseClicked
        // TODO add your handling code here:
        jPanel_AES_btn.setBackground(Color.decode("#2C4F80"));
        jPanel_DES_btn.setBackground(Color.decode("#22416B"));
        jPanel_RSA_btn.setBackground(Color.decode("#22416B"));
        jPanel_MD5_btn.setBackground(Color.decode("#22416B"));
        jPanel_Working_Space.removeAll();
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();

        jPanel_Working_Space.add(jPanel_AES);
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();
    }//GEN-LAST:event_jPanel_AES_btnMouseClicked

    private void jPanel_RSA_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_RSA_btnMouseClicked
        // TODO add your handling code here:
        jPanel_RSA_btn.setBackground(Color.decode("#2C4F80"));
        jPanel_AES_btn.setBackground(Color.decode("#22416B"));
        jPanel_DES_btn.setBackground(Color.decode("#22416B"));
        jPanel_MD5_btn.setBackground(Color.decode("#22416B"));
        jPanel_Working_Space.removeAll();
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();

        jPanel_Working_Space.add(jPanel_RSA);
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();
    }//GEN-LAST:event_jPanel_RSA_btnMouseClicked

    private void jPanel_AESAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel_AESAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_AESAncestorAdded

    private void jPanel_MD5_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_MD5_btnMouseClicked
        // TODO add your handling code here:
        jPanel_MD5_btn.setBackground(Color.decode("#2C4F80"));
        jPanel_AES_btn.setBackground(Color.decode("#22416B"));
        jPanel_RSA_btn.setBackground(Color.decode("#22416B"));
        jPanel_DES_btn.setBackground(Color.decode("#22416B"));
        jPanel_Working_Space.removeAll();
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();

        jPanel_Working_Space.add(jPanel_MD5);
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();
    }//GEN-LAST:event_jPanel_MD5_btnMouseClicked

    private void jTextField_input_hash_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input_hash_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_hash_1ActionPerformed

    private void jTextField_output_hashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_output_hashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_output_hashActionPerformed

    private void jButton_input_hash_btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_input_hash_btn_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_input_hash_btn_1ActionPerformed

    private void jButton_Hash_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Hash_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Hash_btnActionPerformed

    private void jButton_input_hash_btn_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_input_hash_btn_1MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jTextField_input_hash_1.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton_input_hash_btn_1MouseClicked

    private void jButton_Hash_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Hash_btnMouseClicked
        try {
            // TODO add your handling code here:
            String output1=MD5(jTextField_input_hash_1.getText().toString());
            String output2=MD5(jTextField_input_hash_2.getText().toString());
            jTextField_output_hash.setText(output1);
            jTextField_output_hash_1.setText(output2);
            if(output1.equals(output2)) JOptionPane.showMessageDialog(this, "2 ma Hash giong nhau");
            else JOptionPane.showMessageDialog(this, "2 ma Hash khac nhau");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(mm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_Hash_btnMouseClicked

    private void jTextField_input_hash_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input_hash_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_hash_2ActionPerformed

    private void jButton_input_hash_btn_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_input_hash_btn_2MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jTextField_input_hash_2.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton_input_hash_btn_2MouseClicked

    private void jButton_input_hash_btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_input_hash_btn_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_input_hash_btn_2ActionPerformed

    private void jTextField_output_hash_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_output_hash_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_output_hash_1ActionPerformed

    private void jTextField_input_hash_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_input_hash_1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_hash_1MouseClicked

    private void jTextField_input_AESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_input_AESMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_AESMouseClicked

    private void jTextField_input_AESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input_AESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_AESActionPerformed

    private void jButton_input_AES_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_input_AES_btnMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jTextField_input_AES.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton_input_AES_btnMouseClicked

    private void jButton_input_AES_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_input_AES_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_input_AES_btnActionPerformed

    private void jTextField_input_RSAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_input_RSAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_RSAMouseClicked

    private void jTextField_input_RSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input_RSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_RSAActionPerformed

    private void jButton_input_RSA_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_input_RSA_btnMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jTextField_input_RSA.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton_input_RSA_btnMouseClicked

    private void jButton_input_RSA_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_input_RSA_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_input_RSA_btnActionPerformed

    private void jTextField_input_DESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_input_DESMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_DESMouseClicked

    private void jTextField_input_DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input_DESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_DESActionPerformed

    private void jButton_input_DES_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_input_DES_btnMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jTextField_input_DES.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton_input_DES_btnMouseClicked

    private void jButton_input_DES_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_input_DES_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_input_DES_btnActionPerformed

    private void jPanel_MainpageAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel_MainpageAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_MainpageAncestorAdded

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jPanel_MD5_btn.setBackground(Color.decode("#22416B"));
        jPanel_AES_btn.setBackground(Color.decode("#22416B"));
        jPanel_RSA_btn.setBackground(Color.decode("#22416B"));
        jPanel_DES_btn.setBackground(Color.decode("#22416B"));
        jPanel_Working_Space.removeAll();
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();

        jPanel_Working_Space.add(jPanel_Mainpage);
        jPanel_Working_Space.repaint();
        jPanel_Working_Space.revalidate();
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jTextField_input_DES_keyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_input_DES_keyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_DES_keyMouseClicked

    private void jTextField_input_DES_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input_DES_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input_DES_keyActionPerformed

    private void jButton_input_DES_key_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_input_DES_key_btnMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jTextField_input_DES_key.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton_input_DES_key_btnMouseClicked

    private void jButton_input_DES_key_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_input_DES_key_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_input_DES_key_btnActionPerformed

    private void jButton_decrypt_DES_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_decrypt_DES_btnMouseClicked
        // TODO add your handling code here:
        decryptFile(jTextField_input_DES.getText(), jTextField_input_DES_key.getText());
    }//GEN-LAST:event_jButton_decrypt_DES_btnMouseClicked

    private void jButton_decrypt_DES_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_decrypt_DES_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_decrypt_DES_btnActionPerformed

    private void jButton_encrypt_DES_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_encrypt_DES_btnMouseClicked
        // TODO add your handling code here:
        encryptFile(jTextField_input_DES.getText(), jTextField_input_DES_key.getText());
    }//GEN-LAST:event_jButton_encrypt_DES_btnMouseClicked

    private void jButton_encrypt_DES_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_encrypt_DES_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_encrypt_DES_btnActionPerformed
////////////////////////////////////////////////////////////////////////////////////////////////////////
//MD5
    private String MD5(String path) throws FileNotFoundException, NoSuchAlgorithmException, IOException{
        MessageDigest md = MessageDigest.getInstance("MD5");
        FileInputStream fis;
        fis = new FileInputStream(path);

        
        byte[] dataBytes = new byte[1024];
     
        int nread = 0; 
        while ((nread = fis.read(dataBytes)) != -1) {
          md.update(dataBytes, 0, nread);
        };
        byte[] mdbytes = md.digest();
     
        //convert the byte to hex format method 1
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < mdbytes.length; i++) {
          sb.append(Integer.toString((mdbytes[i] & 0xff) + 0x100, 16).substring(1));
        }

        
        //convert the byte to hex format method 2
        StringBuffer hexString = new StringBuffer();
    	for (int i=0;i<mdbytes.length;i++) {
    		String hex=Integer.toHexString(0xff & mdbytes[i]);
   	     	if(hex.length()==1) hexString.append('0');
   	     	hexString.append(hex);
    	}
    	return hexString.toString();
}
    /////////////////////////////////////////////////////////////////////////////////////////////////
    //DES Algorhitm
   

    /////////////////
        private static void encryptFile(String fileName, String keyName)
    {
        
        String original = fileName ;
        String encrypted = "encrypted_" + fileName ;
        System.out.println(fileName);
        Path path = Paths.get(fileName);
        FilenameUtils temp= new FilenameUtils(); //Change separator of path from / to \\
         
        File targetFile;
        System.out.println(temp.separatorsToSystem(path.getParent().toString()));
        targetFile = new File(/*path.getParent().toString()*/ temp.separatorsToSystem(path.getParent().toString()), "encrypted_"+path.getFileName().toString());
        
        Cipher encrypt;
	byte[] initialization_vector = { 22, 33, 11, 44, 55, 99, 66, 77 };
        try
        {
            SecretKey secret_key = readKey(keyName, "DES");
            AlgorithmParameterSpec alogrithm_specs = new IvParameterSpec(initialization_vector);
            encrypt = Cipher.getInstance("DES/CBC/PKCS5Padding");
            encrypt.init(Cipher.ENCRYPT_MODE, secret_key, alogrithm_specs);
            encrypt(new FileInputStream(original), new FileOutputStream(targetFile),encrypt);
            System.out.println("End of Encryption procedure!");
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame("FrameDemo");
            JOptionPane.showMessageDialog(frame, e.toString());
            System.out.println(e.toString());
            System.out.println(e.toString());
        }
    }
    private static void decryptFile(String fileName, String keyName)
    {
        String original = "decrypted_" + fileName;
        String encrypted = fileName ;
        Path path = Paths.get(fileName);
        FilenameUtils temp= new FilenameUtils(); //Change separator of path from / to \\
        File targetFile = new File(temp.separatorsToSystem(path.getParent().toString()), "decrypted_"+path.getFileName().toString());
	Cipher decrypt;
	byte[] initialization_vector = { 22, 33, 11, 44, 55, 99, 66, 77 };
        try
        {
            SecretKey secret_key = readKey(keyName, "DES");
            AlgorithmParameterSpec alogrithm_specs = new IvParameterSpec(initialization_vector);

            decrypt = Cipher.getInstance("DES/CBC/PKCS5Padding");
            decrypt.init(Cipher.DECRYPT_MODE, secret_key, alogrithm_specs);
            decrypt(new FileInputStream(encrypted), new FileOutputStream(targetFile),decrypt);
            System.out.println("End of Decryption procedure!");
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame("FrameDemo");
            JOptionPane.showMessageDialog(frame, e.toString());
            System.out.println(e.toString());
        }
    }

    private static void encrypt(InputStream input, OutputStream output,Cipher encrypt) throws IOException {
        output = new CipherOutputStream(output, encrypt);
        writeBytes(input, output);
    }

    private static void decrypt(InputStream input, OutputStream output,Cipher decrypt) throws IOException {

        input = new CipherInputStream(input, decrypt);
        writeBytes(input, output);
    }
    private static void writeBytes(InputStream input, OutputStream output) throws IOException {
        byte[] writeBuffer = new byte[1024];
        int readBytes = 0;
        while ((readBytes = input.read(writeBuffer)) >= 0) {
            output.write(writeBuffer, 0, readBytes);
        }
        output.close();
        input.close();
    }
    private static void writeKey(int keySize, String output,String algorithm) throws Exception {
        KeyGenerator kg = KeyGenerator.getInstance(algorithm);
        kg.init(keySize);
        System.out.println();
        System.out.println("KeyGenerator Object Info: ");
        System.out.println("Algorithm = " + kg.getAlgorithm());
        System.out.println("Provider = " + kg.getProvider());
        System.out.println("Key Size = " + keySize);
        System.out.println("toString = " + kg.toString());

        SecretKey ky = kg.generateKey();
        byte[] kb;
        try (FileOutputStream fos = new FileOutputStream(output)) {
            kb = ky.getEncoded();
            fos.write(kb);
        }
        System.out.println();
        System.out.println("SecretKey Object Info: ");
        System.out.println("Algorithm = " + ky.getAlgorithm());
        System.out.println("Saved File = " + output);
        System.out.println("Size = " + kb.length);
        System.out.println("Format = " + ky.getFormat());
        System.out.println("toString = " + ky.toString());
    }
    private static SecretKey readKey(String input, String algorithm)throws Exception {
        FileInputStream fis = new FileInputStream(input);
        int kl = fis.available();
        byte[] kb = new byte[kl];
        fis.read(kb);
        fis.close();
        KeySpec ks = null;
        SecretKey ky = null;
        SecretKeyFactory kf = null;
        if (algorithm.equalsIgnoreCase("DES")) {
            ks = new DESKeySpec(kb);
            kf = SecretKeyFactory.getInstance("DES");
            ky = kf.generateSecret(ks);
        } else if (algorithm.equalsIgnoreCase("DESede")) {
            ks = new DESedeKeySpec(kb);
            kf = SecretKeyFactory.getInstance("DESede");
            ky = kf.generateSecret(ks);
        } else {
            ks = new SecretKeySpec(kb, algorithm);
            ky = new SecretKeySpec(kb, algorithm);
        }
        /*
        System.out.println();
        System.out.println("KeySpec Object Info: ");
        System.out.println("Saved File = " + fl);
        System.out.println("Length = " + kb.length);
        System.out.println("toString = " + ks.toString());
        System.out.println();
        System.out.println("SecretKey Object Info: ");
        System.out.println("Algorithm = " + ky.getAlgorithm());
        System.out.println("toString = " + ky.toString());
        */
        return ky;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Hash_btn;
    private javax.swing.JButton jButton_decrypt_DES_btn;
    private javax.swing.JButton jButton_encrypt_DES_btn;
    private javax.swing.JButton jButton_input_AES_btn;
    private javax.swing.JButton jButton_input_DES_btn;
    private javax.swing.JButton jButton_input_DES_key_btn;
    private javax.swing.JButton jButton_input_RSA_btn;
    private javax.swing.JButton jButton_input_hash_btn_1;
    private javax.swing.JButton jButton_input_hash_btn_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_AES;
    private javax.swing.JPanel jPanel_AES_btn;
    private javax.swing.JPanel jPanel_DES;
    private javax.swing.JPanel jPanel_DES_btn;
    private javax.swing.JPanel jPanel_MD5;
    private javax.swing.JPanel jPanel_MD5_btn;
    private javax.swing.JPanel jPanel_Mainpage;
    private javax.swing.JPanel jPanel_RSA;
    private javax.swing.JPanel jPanel_RSA_btn;
    private javax.swing.JPanel jPanel_Working_Space;
    private javax.swing.JTextField jTextField_input_AES;
    private javax.swing.JTextField jTextField_input_DES;
    private javax.swing.JTextField jTextField_input_DES_key;
    private javax.swing.JTextField jTextField_input_RSA;
    private javax.swing.JTextField jTextField_input_hash_1;
    private javax.swing.JTextField jTextField_input_hash_2;
    private javax.swing.JTextField jTextField_output_hash;
    private javax.swing.JTextField jTextField_output_hash_1;
    // End of variables declaration//GEN-END:variables
}
